# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Render-qt
DESTDIR = ./Debug
CONFIG += debug
LIBS += -LE:\Qt\Qt5.14.1\5.14.1\msvc2017\lib\Qt5OpenGL.lib -lopengl32
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(Render-qt.pri)
